"""enterprise_audit_fields

Revision ID: 128be0a252e1
Revises: d2882d769ea4
Create Date: 2026-05-09 15:12:28.351641
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '128be0a252e1'
down_revision: Union[str, None] = 'd2882d769ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crops', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('crops', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('crops', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('expenses', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('expenses', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('mandi_prices', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('mandi_prices', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('mandi_prices', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('predictions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('predictions', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    op.drop_column('predictions', 'is_deleted')
    op.drop_column('predictions', 'updated_at')
    op.drop_column('mandi_prices', 'is_deleted')
    op.drop_column('mandi_prices', 'updated_at')
    op.drop_column('mandi_prices', 'created_at')
    op.drop_column('expenses', 'is_deleted')
    op.drop_column('expenses', 'updated_at')
    op.drop_column('crops', 'is_deleted')
    op.drop_column('crops', 'updated_at')
    op.drop_column('crops', 'created_at')
    # ### end Alembic commands ###
