"""initial_tables

Revision ID: d2882d769ea4
Revises: 
Create Date: 2026-05-09 14:47:11.194275
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'd2882d769ea4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('season', sa.String(length=50), nullable=False),
    sa.Column('average_growth_days', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crops_name'), 'crops', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.String(length=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_mobile'), 'users', ['mobile'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('seed_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fertilizer_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('labour_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('irrigation_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('land_size_acres', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_crop_id'), 'expenses', ['crop_id'], unique=False)
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    op.create_table('mandi_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('mandi_name', sa.String(length=200), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('modal_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mandi_prices_arrival_date'), 'mandi_prices', ['arrival_date'], unique=False)
    op.create_index(op.f('ix_mandi_prices_crop_id'), 'mandi_prices', ['crop_id'], unique=False)
    op.create_index(op.f('ix_mandi_prices_district'), 'mandi_prices', ['district'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('predicted_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('trend', sa.String(length=10), nullable=True),
    sa.Column('prediction_month', sa.Date(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_crop_id'), 'predictions', ['crop_id'], unique=False)
    op.create_index(op.f('ix_predictions_district'), 'predictions', ['district'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_district'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_crop_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_mandi_prices_district'), table_name='mandi_prices')
    op.drop_index(op.f('ix_mandi_prices_crop_id'), table_name='mandi_prices')
    op.drop_index(op.f('ix_mandi_prices_arrival_date'), table_name='mandi_prices')
    op.drop_table('mandi_prices')
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_crop_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_mobile'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_crops_name'), table_name='crops')
    op.drop_table('crops')
    # ### end Alembic commands ###
